// No JS-invokable commands of this plugin's own (lib.rs's own header
// comment) — empty COMMANDS means `permissions/autogenerated/` ends up
// empty too; `permissions/default.toml` grants the two framework-
// provided listener commands via a HAND-written permission file instead
// (see that directory's own header comment).
const COMMANDS: &[&str] = &[];

fn main() {
  tauri_plugin::Builder::new(COMMANDS)
    .ios_path("ios")
    .build();
}
